name: "Run golangci-lint"
github-token:
  action-input: 
    input: github-token
    is-default: true
  permissions:
    pull-requests: read
    pull-requests-reason: to fetch pull requests

# NOTE: Solves#197