name: 'Fetch Metadata from Dependabot PRs'
#No Permission is needed for action step. 
#Permissions for Run steps like(auto-approve, auto-merge and auto-label) is added in pemissions.go file.
#Reference: https://github.com/dependabot/fetch-metadata#usage-instructions