name: "Google Java Format"
github-token:
  action-input:
    input: githubToken
  permissions:
    contents: read
    contents-reason: to get releases #Checkout: https://github.com/axel-op/googlejavaformat-action#githubtoken

# FIX: #451