name: 'Super-Linter slim'
github-token:
  environment-variable-name: GITHUB_TOKEN
  is-default: false
  permissions:
    checks: write
    checks-reason: to update Checks Section # CHECKOUT: https://github.com/github/super-linter#how-to-use
  
# FIX#192