name: "ESLint Annotate from Report JSON"
github-token:
  action-input:
    input: repo-token
  permissions:
    checks: write
    checks-reason: to  #Checkout: https://github.com/ataylorme/eslint-annotate-action/blob/a1bf7cb320a18aa53cb848a267ce9b7417221526/src/eslint-action.ts#L82