name: 'Deploy to Kubernetes cluster'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    contents: read
    contents-reason: to query workflow path
    issues: write
    issues-reason: to set issues as idle
    pull-requests: write
    pull-requests-reason: to set PRs as idle
    
harden-runner-link: https://app.stepsecurity.io/github/arjundashrath/StepSecurity_Tests/actions/runs/1729871674 
