name: 'cache-extensions'
outbound-endpoints:
  api.github.com:443:
    port: 443
    reason: to call GitHub API
  github.com:443:
    port: 443
    reason: to download scripts from GitHub
  objects.githubusercontent.com:443:
    port: 443
    reason: to fetch git object
  ppa.launchpad.net:80:
    port: 443
    reason: to get package files from launchpad PPA
  artifactcache.actions.githubusercontent.com:443:  
    port: 443
    reason: to cache files
  vstsmms.actions.githubusercontent.com:443:
    port: 443
    reason: to cache files
  pipelines.actions.githubusercontent.com:443:
    port: 443
    reason: to restore cached files
  prtcacprodeus2file7.blob.core.windows.net:443:
    port: 443
    reason: to restore cached files
harden-runner-link: https://app.stepsecurity.io/github/shivammathur/test-setup-php/actions/runs/1539305900
