name: 'Auto Approve'
github-token:
  action-input:
    input: github-token
    is-default: true
  permissions:
    pull-requests: write
    pull-requests-reason: to create review or approve PRs #Checkout: 
#Fixes #505