name: "Label Conflicting Pull Requests"
github-token:
  action-input:
    input: repoToken
    is-default: false
  permissions:
    issues: write
    issues-reason: to tag/untag PRs
#Reference: https://github.com/eps1lon/actions-label-merge-conflict/blob/a2389f3d584f2f820277e63d9b7310622657a887/sources/main.ts#L333
