name: 'Codacy Analysis CLI'
outbound-endpoints:
  - fqdn: raw.githubusercontent.com
    port: 443
    reason: to fetch source code
  - fqdn: '*.docker.io'
    port: 443
    reason: to access docker 
  - fqdn: auth.docker.io
    port: 443
    reason: to authenticate docker credentials
  - fqdn: production.cloudflare.docker.com
    port: 443
    reason: to fetch content
  - fqdn: api.codacy.com
    port: 443
    reason: to fetch codacy configuration  
harden-runner-link: https://app.stepsecurity.io/github/arjundashrath/StepSecurity_Tests/actions/runs/1722954530
