name: 'Pull Request size labeler'
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: false
  permissions:
    pull-requests: write
    pull-requests-reason: to add labels & comment on PRs #Checkout: https://github.com/bflad/pr-size-labeler/blob/master/src/github.sh#L15 

#Fixes #523