name: OpenShift Login

outbound-endpoints:
  - fqdn: *.openshift-online.com # NOTE: https://stackoverflow.com/questions/46417232/what-server-url-should-be-used-for-the-oc-login-command-when-using-openshifts 
    port: 6443
    reason: to perform authentication in RedHat OpenShift