name: 'Codecov'
outbound-endpoints:
  storage.googleapis.com:
    port: 443
    reason: to upload coverage report
  uploader.codecov.io:
    port: 443
    reason: to download codecov uploader
  codecov.io:
    port: 443
    reason: to download codecov uploader  
harden-runner-link: https://app.stepsecurity.io/github/step-security/secure-workflows/actions/runs/1533156019