name: 'setup-php'
github-token:
  environment-variable-name: COMPOSER_TOKEN
  permissions:
    contents: read
    contents-reason: to access matching refs GitHub API, clone the repos, and get release assets.
outbound-endpoints:
  api.github.com:443:
    port: 443
    reason: to call GitHub API
  api.launchpad.net:443:
    port: 443
    reason: to call launchpad API
  archive.ubuntu.com:443:
    port: 443
    reason: to download packages from ubuntu archives
  archive.ubuntu.com:80:
    port: 80
    reason: to download packages from ubuntu archives
  azure.archive.ubuntu.com:443:
    port: 443
    reason: to download packages from azure mirror of ubuntu archives
  azure.archive.ubuntu.com:80:
    port: 80
    reason: to download packages from azure mirror of ubuntu archives
  bazel.build:443:
    port: 80
    reason: to download bazel GPG key
  blackfire.io:443:
    port: 443
    reason: to set-up Blackfire
  cdn.jsdelivr.net:
    port: 443
    reason: fallback CDN for scripts
  codeload.github.com:443:
    port: 443
    reason: to call GitHub release assets
  deployer.org:443:
    port: 443
    reason: to download Deployer phar
  downloads.ioncube.com:443:
    port: 443
    reason: to download ionCube extension
  download.oracle.com:443:
    port: 443
    reason: to download Oracle instantclient
  get.Blackfire.io:443:
    port: 443
    reason: to set-up Blackfire
  getcomposer.org:443:
    port: 443
    reason: fallback for Composer phars
  git.remirepo.net:
    port: 443
    reason: to download patches
  github-releases.githubusercontent.com:443:
    port: 443
    reason: to get GitHub release information
  github.com:443:
    port: 443
    reason: to download scripts from GitHub
  keyserver.ubuntu.com:443:
    port: 443
    reason: to fetch PPA keys
  objects.githubusercontent.com:443:
    port: 443
    reason: to fetch git objects
  packages.Blackfire.io:443:
    port: 443
    reason: to set-up Blackfire
  packages.Blackfire.io:80:
    port: 80
    reason: to set-up Blackfire
  packages.sury.org:443:
    port: 443
    reason: to get PHP packages on Debian
  packages.sury.org:80:
    port: 80
    reason: to get PHP packages on Debian
  pear.php.net:443:
    port: 443
    reason: to set-up PHP extensions
  pear.php.net:80:
    port: 80
    reason: to set-up PHP extensions
  pecl.php.net:443:
    port: 443
    reason: to set-up PHP extensions
  pecl.php.net:80:
    port: 80
    reason: to set-up PHP extensions
  phar.io:443:
    port: 443
    reason: to download Phive phar
  phar.phpunit.de:443:
    port: 443
    reason: to download PHPUnit and related phars
  ppa.launchpad.net:80:
    port: 80
    reason: to get PPA fingerprint
  raw.githubusercontent.com:443:
    port: 443
    reason: to download raw files on GitHub
  repo.packagist.org:443:
    port: 443
    reason: to get packages manifests using Composer
  setup-php.com:443:
    port: 443
    reason: to set-up PPA mirrors, scripts and patches
  storage.googleapis.com:443:
    port: 443
    reason: to set-up Bazel
  www.phing.info:443:
    port: 443
    reason: to download phing phar
harden-runner-link: https://app.stepsecurity.io/github/shivammathur/test-setup-php/actions/runs/1539115993
