name: 'ACR-Login action'
outbound-endpoints:
  - fqdn: 'cr.*.aliyuncs.com'
    port: 443
    reason: get api endpoints

  - fqdn: 'registry.*.aliyuncs.com'
    port: 443
    reason: get registry endpoints

  - fqdn: index.docker.io
    port: 443
    reason: logging into the server
