name: no-actions
on:
  workflow_dispatch
jobs:
  list-directory:
    runs-on: ubuntu-latest
    steps:
     - uses: step-security/harden-runner@main
     - run: ls -R
  list-directory1:
    runs-on: ubuntu-latest
    steps:
     - run: ls -R