name: 'Docker Metadata action'
github-token:
  action-input:
    input: github-token
    is-default: true
  permissions:
    contents: read
    contents-reason: to query repo information
outbound-endpoints:
  - fqdn: api.github.com
    port: 443
    reason: to query repo information
harden-runner-link: https://app.stepsecurity.io/github/microsoft/msquic/actions/runs/1723947678