name: KBAnalysis
on:
  issues:
    types:
     - opened
     - reopened
     - closed
permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: step-security/secure-workflows
    
      - name: KBAnalysis
        uses: step-security/secure-workflows/kbanalysis@main
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.PAT}} #  need to use PAT since GITHUB_TOKEN does not initiate workflows
          body: "Fixes #${{github.event.issue.number}}"
          commit-message: "added KB for issue#${{github.event.issue.number}}"
          title: "Add KB for issue${{github.event.issue.number}}"
          branch: "issue#${{github.event.issue.number}}"
